[package]
name = "slatedb_estimates"
version = "0.1.0"
edition = "2024"

[dependencies]
slatedb = { git = "https://github.com/slatedb/slatedb", rev = "e4a31506e78878e313a001e0ade760ddbda59dba", default-features = false }

[dev-dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
